# Generated by Django 3.1.4 on 2021-01-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventpage_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='start'),
        ),
    ]
