# Generated by Django 3.1.4 on 2021-01-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210108_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='end'),
        ),
    ]
