# Generated by Django 3.1.4 on 2021-01-09 19:34

from django.db import migrations
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_author'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('events', '0006_eventauthorsorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='streams.Category'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='streams.PageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
