# Generated by Django 3.1.4 on 2021-01-09 20:13

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('events', '0008_eventpagetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='events.EventPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
