# Generated by Django 3.1.4 on 2020-12-30 02:25

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_pagetag'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0002_postpage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='streams.PageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
