# Generated by Django 3.1.4 on 2020-12-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201231_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='body',
        ),
    ]
