# Generated by Django 3.1.4 on 2021-01-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
