# Generated by Django 3.1.4 on 2021-01-09 19:44

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201231_0458'),
        ('streams', '0005_auto_20210109_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagetag',
            name='content_object_blog',
        ),
        migrations.RemoveField(
            model_name='pagetag',
            name='content_object_events',
        ),
        migrations.AddField(
            model_name='pagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pythonclassmates_tag', to='home.homepage'),
        ),
    ]
