# Generated by Django 3.1.4 on 2021-01-09 19:48

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201231_0458'),
        ('streams', '0006_auto_20210109_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='home.homepage'),
        ),
    ]
