# Generated by Django 3.1.4 on 2021-01-09 19:55

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210109_1934'),
        ('streams', '0007_auto_20210109_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_tags', to='events.eventpage'),
        ),
    ]
