# Generated by Django 3.1.4 on 2021-01-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0009_auto_20210109_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
