# Generated by Django 3.1.4 on 2021-01-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcespage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
