# Generated by Django 3.1.4 on 2021-01-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourcespage_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcepage',
            options={'verbose_name': 'Resource Page', 'verbose_name_plural': 'Resource pages'},
        ),
        migrations.AlterModelOptions(
            name='resourcespage',
            options={'verbose_name': 'Resources Page', 'verbose_name_plural': 'Resources Pages'},
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='custom_title',
            field=models.CharField(help_text='Overwrites the default title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
