# Generated by Django 3.1.4 on 2021-01-12 22:48

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('resources', '0004_resourcetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='resources.ResourceTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
